<template lang="pug">
.page-nft-all.text-left
  .container.pt-5.pb-5(v-if="!workName")
    a.row.py-3.nft-item(
      href="https://www.fxhash.xyz/generative/slug/soulfish",
      target="_blank"
    )
      .col-5
        iframe.w-100(
          src="https://gateway.fxhash2.xyz/ipfs/QmWYvkFHPLBkmv1CSCK5vpm3MSBggbALDqRZQXitzPPLJn/?fxhash=oodGicCkjQy2pe9gZLrDXhTnYHP4hfsKY1QizPyuRdmVNzvUEzu",
          style="width: 100%; aspect-ratio: 1; border: none"
        )

        //- img.w-100(
        //-   src="https://gateway.fxhash2.xyz/ipfs/QmSjD9c2S8tN4f8QpJSRtxHhkKRtpiA8LmEoNRWAdxANW7",
        //-   alt=""
        //- )
      .col-7
        h2 SoulFish
        h3 
        h5 fxhash, June 2nd 2022, 1000 editions
        p Named after the artist Wu Che-Yu, the soul fish was born in the void and crystallized from human emotions.
        p Fluttering silently and slowly, their bodies almost disappeared in the light of the deep sea.<br></br>The fish swims freely, and this is the happiness of the fish.
        p If we are not a fish, how do we know the joy of a fish?<br>How do we know that we do not know the joy of fish?
        p We will only learn about it when we come to the riverside.

    a.row.py-3.nft-item(
      href="https://www.fxhash.xyz/generative/5438",
      target="_blank"
    )
      .col-5
        img.w-100(
          src="https://gateway.fxhash2.xyz/ipfs/QmSjD9c2S8tN4f8QpJSRtxHhkKRtpiA8LmEoNRWAdxANW7",
          alt=""
        )

        //- iframe.w-100(
        //-   src="https://gateway.fxhash2.xyz/ipfs/QmPDfMShxb1iQ12bwV4LivT5pC1UXoL9ZRcjjC7grr3r9P/?fxhash=ooto45sU86CaUZFWxUduRyCPqRYpVoSmKrcRcrkJ8DCxwziDb6o",
        //-   style="width: 100%; aspect-ratio: 1; border: none"
        //- )
      .col-7
        h2 SoulSea
        h3 
        h5 fxhash, Dec 29th 2021, 300 editions
        p You look down and find that the ocean in your heart is a sine wave.<br>The tide gently laps onto the shore.
        p The soul is the sea. You are the land.<br/>There are waves on the shore, and the waves are slices.
        p Gazing at the slices, you feel the coldness of the Arctic Ocean, the permafrost of the Antarctic Sea, the deep darkness of the bottomless sea.
        p Stay silent, hear the sound of the waves lapping at the innumerable shores far away.<br>Feel the soul of the digital ocean.

    a.row.py-3.nft-item(
      href="https://www.fxhash.xyz/generative/5438",
      target="_blank"
    )
      .col-5
        img.w-100(
          src="https://doodlelabs.mo.cloudinary.net/mainnet/1001272.png?tx=w_300",
          alt=""
        )
      .col-7
        h2 Sliderverse
        h3 
        h5 Doodle Lab, Dec 15th 2021 | 1284/5001 editions
        p In honor of White Castle’s 100th Birthday, renowned multimedia artist Che-Yu Wu has reimagined the White Castle menu through a generative art lens. Each unique edition within this series of collectible NFTs is generated by an algorithm at the time of mint, pushing the boundaries of physics, mathematics, and art. This series combines Che-Yu’s signature, interactive style with White Castle’s legendary sliders to explore the intersection between food, art, tech and culture.
        p And in keeping with White Castle’s spirit of feeding the souls of their communities and team members, a portion of the proceeds from Sliderverse will directly benefit our Team Member Relief Fund and the Ingram-White Castle Team Member Scholarship.

    router-link.row.py-3.nft-item(to="/nft/electriz")
      .col-5
        img.w-100(src="https://media.artblocks.io/216000000.png", alt="")
      .col-7
        h2 Electriz
        h3 
        h5 Artblocks, Dec 7th 2021, 910 editions
        p "Electriz" is a series of works that use digital cloud chambers to observe the traces of unidentified particles. When doing art creation, just like scientists discovering new particles, artists continue to draw interesting ideas from reality and fantasy to collide with each other, trying to find a unique existence at the moment of collision in the process of mixing ideas.
        p The space in the work "Electriz" is divided into parts with different physical characteristics, which affect the movement, rotation, splitting, and annihilation of particles. It is an unpredictable experimental system with unlimited possibilities to explore the intersection of physics, mathematics, and art.

    a.row.py-3.nft-item(href="https://cryptopochi.com/", target="_blank")
      .col-5
        img.w-100(
          src="https://pochi.nyc3.digitaloceanspaces.com/mainnet/0x26cb33fba22f213952b8b3f3af006913b6c5b5e91081bb5c9c7764c66c98b44b.gif",
          alt=""
        )
      .col-7
        h2 Crypto Pochi
        h3 
        h5 Sep 5th 2021 | 732/732 editions
        p CryptoPochis are mysterious creatures that capture different emotions in your daily life. Their faces speak for themselves. They simply lie on the ground and play all day. We catch and wrap them as NFTs for you to play with.
  PageNftElectriz(v-if="workName == 'electriz'")
</template>

<script>
import ElectrizDemo from "@/components/ElectrizDemo";
import PageNftElectriz from "./pageNftElectriz";
export default {
  computed: {
    workName() {
      return this.$route.params.name;
    },
  },
  components: {
    ElectrizDemo,
    PageNftElectriz,
  },
};
</script>

<style lang="sass">
@import url('https://fonts.googleapis.com/css2?family=Rokkitt:wght@100;200;300;400;500;600;700;800;900&display=swap')
.page-nft-all
  background-color: black
  color: white
  h2
    margin-top: 50px
  a
    color: white
    &:hover
      text-decoration: none
  .container
    max-width: 1200px
  .nft-item
    border: solid 1px rgba(white,0.3)
    transition: 0.2s
    margin-top: 30px
    border-radius: 10px
    &:hover
      background-color: rgba(white,0.1)
</style>
